name: Deploy WordPress Theme & Plugin

# Kích hoạt khi push lên branch main
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Thiết lập SSH để kết nối server
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Deploy Theme
      - name: Deploy Theme
        run: |
          rsync -avz --delete ./themes/unmnmnc/ root@45.76.162.54:/var/www/html/wp-content/themes/unmnmnc-theme

      # 4. Deploy Plugin
      - name: Deploy Plugin
        run: |
          rsync -avz --delete ./plugins/ root@45.76.162.54:/var/www/html/wp-content/plugins/unmnmnc-plugin
