name: 🚀 Deploy WordPress Theme & Plugins to VPS

on:
  push:
    branches: [ "main" ]        # ✅ Tự động chạy khi bạn push code lên branch main
    paths:
      - 'themes/**'              # Nếu có thay đổi trong thư mục themes
      - 'plugins/**'             # hoặc plugins thì workflow sẽ kích hoạt
  workflow_dispatch: {}           # ✅ Cho phép bạn tự bấm "Run workflow" thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest        # ✅ Máy ảo Ubuntu mới nhất để chạy workflow

    steps:
      # 🧱 1. Lấy code mới nhất từ GitHub repo của bạn
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1          # Chỉ tải commit mới nhất cho nhanh

      # 🔑 2. Thiết lập SSH để GitHub có thể truy cập vào VPS của bạn
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}   # Private key bạn đã add vào Secrets

      # 🧠 3. Thêm "known_hosts" để tránh lỗi xác thực SSH lần đầu
      - name: Add known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      # 📦 4. Upload themes và plugins từ GitHub sang thư mục tạm trên VPS (không cần sudo)
      - name: Upload themes & plugins to tmp
        run: |
          TMP_DIR="~/deploy_tmp"
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p $TMP_DIR/themes $TMP_DIR/plugins"
          
          # 🧩 Đồng bộ theme
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            --exclude '.git' --exclude '.github' --exclude 'node_modules' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            themes/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$TMP_DIR/themes/

          # 🧩 Đồng bộ plugin
          rsync -az --delete \
            --omit-dir-times --no-perms --no-owner --no-group \
            --exclude '.git' --exclude '.github' --exclude 'node_modules' \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            plugins/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:$TMP_DIR/plugins/

      # ⚙️ 5. Di chuyển từ thư mục tạm sang thư mục WordPress chính trên server
      - name: Move to WordPress directory with sudo
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e

          TMP_DIR="$HOME/deploy_tmp"
          TARGET="${{ secrets.TARGET_DIR }}/wp-content"

          # ✅ Đảm bảo thư mục đích tồn tại
          sudo mkdir -p "$TARGET/themes" "$TARGET/plugins"

          # 🚀 Rsync (copy có đồng bộ, xóa file thừa)
          sudo rsync -a --delete "$TMP_DIR/themes/" "$TARGET/themes/"
          sudo rsync -a --delete "$TMP_DIR/plugins/" "$TARGET/plugins/"

          # 🔒 Set quyền chính xác để WordPress truy cập được
          sudo chown -R www-data:www-data "$TARGET/themes" "$TARGET/plugins"
          sudo find "$TARGET/themes" -type d -exec chmod 755 {} \;
          sudo find "$TARGET/themes" -type f -exec chmod 644 {} \;
          sudo find "$TARGET/plugins" -type d -exec chmod 755 {} \;
          sudo find "$TARGET/plugins" -type f -exec chmod 644 {} \;

          # 🔄 Reload PHP-FPM & Web server (nếu có)
          sudo systemctl reload php8.1-fpm || sudo systemctl reload php8.2-fpm || true
          sudo systemctl reload nginx || sudo systemctl reload apache2 || true
          EOF
